blog/urls.py
from django.urls import path

from .views import artiles_content

urlpatterns = [
	path('articles-content', artiles_content, name='articles_content')
]

calen_blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from graphene_django.views import GraphQLView
from search import views as search_views

from blog import views as blog_views

urlpatterns = [
	url(r'^django-admin/', admin.site.urls),

	url(r'^calenadmin/', include(wagtailadmin_urls)),
	url(r'^documents/', include(wagtaildocs_urls)),

	url(r'^search/$', search_views.search, name='search'),
	path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
	path('sitemap.xml', sitemap),
	path('graphql',  csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

handler500 = blog_views.handler500

if settings.DEBUG:
	from django.conf.urls.static import static
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns
	import debug_toolbar

	# Serve static and media files from development server
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns = [
		path('__debug__/', include(debug_toolbar.urls))
	] + urlpatterns

urlpatterns = urlpatterns + [
	# For anything not caught by a more specific rule above, hand over to
	# Wagtail's page serving mechanism. This should be the last pattern in
	# the list:
	url(r"", include(wagtail_urls)),

	# Alternatively, if you want Wagtail pages to be served from a subpath
	# of your site, rather than the site root:
	#	url(r"^pages/", include(wagtail_urls)),
]

blog/models.py
"""Blog listing and blog detail pages"""
from django import forms
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import models
from django.shortcuts import render

from django_extensions.db.fields import AutoSlugField

from modelcluster.models import ClusterableModel, ParentalKey, ParentalManyToManyField
from modelcluster.contrib.taggit import ClusterTaggableManager
#in line 44, add {} to _to_tag_model_instances = tag_objs = self._to_tag_model_instances(tags, {})

from taggit.models import TaggedItemBase

from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel, StreamFieldPanel, InlinePanel, MultiFieldPanel
from wagtail.contrib.routable_page.models import RoutablePageMixin, route
from wagtail.core.fields import StreamField
from wagtail.core.models import Page, Orderable
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.snippets.models import register_snippet

from streams import blocks

from account.models import User


class ListingPage(RoutablePageMixin, Page):
	"""Listing page lists all the Blog Detail Pages."""
	max_count = 1
	template = 'blog/listing.html'
	subpage_types = ['ArticlePage']

	def get_admin_display_title(self):
		return 'Blog Listing Page'

	def __str__(self):
		return 'Blog Listing Page'

	def get_context(self, request, *args, **kwargs):
		context = super().get_context(request, *args, **kwargs)
		context['listing_url'] = self.url
		context['page'] = request.GET.get('page', None)
		context['tags'] = request.GET.get('tags', None)
		context['search'] = request.GET.get('search', None)
		searches = None
		if context['search'] and context['search'] != 'None':
			context['searches'] = context['search'].split(';;;')[:-1]
			context['search'].replace(';;;', ',')
		return context


class Tag(TaggedItemBase):
	content_object = ParentalKey(
		'ArticlePage',
		related_name='blog_tags',
		on_delete=models.CASCADE
	) #cant change name


class AuthorsOrderable(Orderable):
	""""""
	page = ParentalKey('ArticlePage', related_name='blog_authors')
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	unique_together = ('page', 'author')
	panels = [SnippetChooserPanel('author'),]


class Category(ClusterableModel):
	"""Category for a snippet."""
	name = models.CharField(max_length=255)
	slug = AutoSlugField(populate_from='name', editable=True)

	panels = [
		FieldPanel('name'),
		FieldPanel('slug'),
	]

	class Meta:
		verbose_name = 'Category'
		verbose_name_plural = 'Blog Categories'
		ordering = ['name']

	def __str__(self):
		return self.name
register_snippet(Category)


class CategoriesOrderable(Orderable, Category):
	""""""
	page = ParentalKey('ArticlePage', related_name='blog_categories')


class ArticlePage(RoutablePageMixin, Page):
	"""Blog Artice"""
	subpage_types = []
	parent_page_types = [ListingPage]
	tags = ClusterTaggableManager(through=Tag, blank=True)
	template = 'blog/article.html'
	subtitle = models.CharField(max_length=255, blank=True, null=True, help_text='Why we love Avicii')
	authors = ParentalManyToManyField(User, blank=False, related_name='blog_authors')
	categories = ParentalManyToManyField(Category, blank=True, null=True, related_name='blog_categories')
	preview_image = models.ForeignKey(
		'wagtailimages.Image',
		blank=True,
		null=True,
		related_name='+',
		on_delete=models.SET_NULL
	)
	preview_text = models.TextField(blank=True, null=True)
	content = StreamField(
		[
			('richtext', blocks.RichtextBlock()),
			('code', blocks.CodeBlock()),
			('html', blocks.HtmlBlock())
		], 
		null=True,
		blank=True
	)
	content_panels = Page.content_panels + [
		FieldPanel('subtitle'),
		ImageChooserPanel('preview_image'),
		FieldPanel('preview_text'),
		MultiFieldPanel(
			[
				#FieldPanel('authors', widget=forms.CheckboxSelectMultiple)
				FieldPanel('authors', widget=forms.CheckboxSelectMultiple)
			], heading='Author(s)'
		),
		MultiFieldPanel(
			[
				InlinePanel('blog_categories')
			], heading='Categories'
		),
		FieldPanel('tags'),
		StreamFieldPanel('content')
	]

	def save(self, *args, **kwargs):
		key = make_template_fragment_key('article', [self.id])
		cache.delete(key)
		return super().save(*args, **kwargs)


"""
class Category(models.Model):
	"Category for a snippet.""
	name = models.CharField(max_length=255)
	slug = AutoSlugField(populate_from='name', editable=True)

	panels = [
		FieldPanel('name'),
		FieldPanel('slug'),
	]

	class Meta:
		verbose_name = 'Category'
		verbose_name_plural = 'Blog Categories'
		ordering = ['name']

	def __str__(self):
		return self.name
register_snippet(Category)
"""

blog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ArticlesFilterForm(forms.Form):
  search = forms.CharField(
    label=_('Search'),
    widget=forms.TextInput(attrs={'type': 'text', 'placeholder': _('Search')})
  )

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from functools import reduce

from account.models import User
from .forms import ArticlesFilterForm
from .models import ListingPage, ArticlePage

import operator

def get_paginator_items(paginator, page):
	"""
	Get paginatior items
	"""
	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		items = paginator.page(1)
	except EmptyPage:
		items = paginator.page(paginator.num_pages)
	return items


def get_page_from_request(request):
	return request.GET.get('page')


def artiles_content(request):
	"""
	Articles list content view
	"""
	searches = None
	search = request.GET.get('search', None)
	articles = ArticlePage.objects.live().public().order_by('-first_published_at')
	if search:
		empty = False
		searches = search.split(';;;')[:-1]
		all_authors = User.objects.all()
		for search_block in searches:
			search_blocks = search_block.split(': ', 1)
			if search_blocks[0] == 'article':
				articles = articles.filter(title=search_blocks[1])
			elif search_blocks[0] == 'tag':
				articles = articles.filter(tags__name__in=[search_blocks[1]])
			elif search_blocks[0] == 'author':
				found = False
				for author in all_authors:
					if str(author) == search_blocks[1]:
						articles = articles.filter(authors__pk=author.pk)
						found = True
				if not found:
					articles = []
			elif search_blocks[0] == 'category':
				articles = articles.filter(categories__name__contains=search_blocks[1])
			else:
				articles = articles.filter(title__contains=search_blocks[0])
			if not articles:
				articles = ArticlePage.objects.filter(title='ajdsfljlksjdfklioewwmncgdfkeiwk')
				break
	page = get_page_from_request(request)
	return render(request, 'blog/listing_content.html', {
		'articles': get_paginator_items(Paginator(articles, 12), page),
		'page': page,
		'searches': searches,
		'listing_url': ListingPage.objects.all().first().url
	})


def handler500(request):
	return render(request, '500.html', status=500)

blog/templates/blog/listing.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load wagtailcore_tags wagtailroutablepage_tags %}
{% block title %}
  {% trans 'Articles' %}
{% endblock %}
{% block head %}
  <meta name="theme-color" content="#0C4B33"/>
  <meta name="description" content="{{ self.title }}" />
  <link rel="stylesheet" href="{% static 'vendors/tagify/tagify.css' %}">
{% endblock %}
{% block bodytag %}style="background-color: #0C4B33;"{% endblock %}
{% block overlay %}
  <div id="articles-search-bar" class="bg-white position-absolute articles-search-bar">
    <form id="articles-filter-form" class="d-flex w-100 h-100 align-items-center max-width-medium m-auto"
      onSubmit="e.preventDefault(); submitArticlesFilterForm();">
      <div>
        <div class="pl-3 pr-3 pl-md-4 pr-md-4 cursor-pointer" onClick="hideSearch();">
          <i class="icon-cancel color-primary"></i>
        </div>
      </div>
      <div class="w-100">
				<input id="articles-filter-search" class="basic-form-input invisible-input" name="search" 
					placeholder="{% trans 'Search' %}" aria-label="{% trans 'Keyword' %}"/>
      </div>
      <div>
        <div class="pl-3 pr-3 pl-md-4 pr-md-4 cursor-pointer" onClick="submitArticlesFilterForm();">
          <i class="icon-search color-primary"></i>
        </div>
      </div>
    </form>
  </div>
  <div class="d-block d-md-none mt-3 mr-3 position-fixed" style="top: 64px; right: 0px; z-index: 1;">
    <div id="articles-search-button-mobile" 
      class="rounded-circle border border-thick border-white p-2 cursor-pointer sligh-box-shadow bg-primary" 
      onClick="showSearch();">
      <div class="d-flex justify-content-center align-items-center" style="width: 32px; height:32px;">
        <i class="icon-search font color-white z-index: 1;"></i>
      </div>
    </div>
  </div>
{% endblock %}
{% block content %}
<div style="color: #ffffff;">
  <div class="d-flex align-items-center position-relative mt-4">
    <div>
      <h1 id="articles-title">{{ self.title }}</h1>
    </div>
    <div class="rounded-circle border border-thick border-white p-2 cursor-pointer ml-3 d-none d-md-block" 
      onClick="showSearch();">
      <div class="d-flex justify-content-center align-items-center" style="width: 32px; height:32px;">
        <i class="icon-search font color-white z-index: 1;"></i>
      </div>
    </div>
  </div>
  <div id="articles-content" class="mt-5"></div>
</div>
<script src="{% static 'vendors/tagify/tagify.min.js' %}"></script>
<script>
	let tagify = null;
  firstSearch = true;
  document.addEventListener('DOMContentLoaded', () => {
		let container = document.getElementById('articles-content');
		removeAllChilds(container);
		container.appendChild(getArticlesSkeleton());
  });
  function loadArticles(newUrl, pushUrl=false){
    idk(newUrl, pushUrl);
    return false;
  }
  async function idk(newUrl, pushUrl=false){
    await loadContentSkeleton('articles-content', newUrl, getArticlesSkeleton());
    if (pushUrl == true){
      const urlParas = newUrl.split('?');
      if (urlParas.length > 1) {
        window.history.pushState('', '', '{{ listing_url }}?' + newUrl.split('?')[1]);
      }else{
        window.history.pushState('', '', '{{ listing_url }}');
      }
    }
    setTimeout(() => {
      let imageElements = document.getElementsByClassName('article-preview-image');
      for(let i = 0;i < imageElements.length; i++){
        imageElements[0].style.backgroundImage = imageElements[0].getAttribute('data-background-image');
      }
      randomizeShowingPreview();
    }, 500);
  }
  function showSearch() {
    document.getElementById('articles-search-bar').classList.add('d-md-block');
    setTimeout(function(){
      document.getElementById('articles-search-bar').classList.add('is-active');
    }, 1);
    setTimeout(function(){
      document.getElementById('main-block').addEventListener('click', hideSearch);
    }, 1);
    setTimeout(function(){
      document.getElementById('articles-filter-search').focus();
      document.getElementById('articles-filter-search').select();
    }, 10);
  }
  function hideSearch() {
    document.getElementById('articles-search-bar').classList.remove('is-active');
    document.getElementById('main-block').removeEventListener(
      'click', hideSearch
    )
  }
	async function submitArticlesFilterForm() {
    let page = '';
    let newUrl = new URL(window.location.origin + '{% url "blog:articles_content" %}');
    let displayUrl = new URL(window.location.origin + '{{ listing_url }}');
		const search = document.getElementById('articles-filter-search').value;
		if (search) {
			const searchJson = JSON.parse('{"search":' + search + '}');
			let searchString = '';
			searchJson.search.forEach((dictio) => {
				searchString += dictio.value + ';;;';
			})
			if (search != null || search != '') {
				newUrl.searchParams.append('search', searchString);
				displayUrl.searchParams.append('search', searchString);
			}
		}
    if (firstSearch == false){
      window.history.pushState('', '', displayUrl);
      hideSearch();
    } else {
      firstSearch = false;
    }
    loadArticles(newUrl);
  }
  function randomizeShowingPreview() {
    let hiddenArticleOverlays = document.getElementsByClassName('article-hidden-overlay');
    for(let i = 0;i < hiddenArticleOverlays.length; i++){
      loopActive(hiddenArticleOverlays[i]);
    }
  }
  async function loopActive(element) {
    const start = Math.floor((Math.random() * 5000) + 1);
    const timeout = Math.floor((Math.random() * 2000) + 3000);
    await new Promise(resolve => setTimeout(resolve, timeout));
    for (item of new Array(1000)){
      await sleep(timeout);
      element.classList.add('active');
      await sleep(timeout);
      element.classList.remove('active');
    }
  }
  function getArticleSkeleton() {
    let megaDiv = setAttributes(document.createElement('div'), {
      'class': 'col-12 col-sm-6 col-xl-4 mb-5 article',
      'style': 'min-height: 320px;'
    });
    let borderDiv = setAttributes(document.createElement('div'), {
      'class': 'skeleton-border p-3 d-flex flex-column justify-content-between h-100'
    });
    let topDiv = setAttributes(document.createElement('div'), {});
    let h5 = setAttributes(document.createElement('div'), {
      'class': 'h5-skeleton skeleton-animate'
    });
    let h2 = setAttributes(document.createElement('div'), {
      'class': 'h2-skeleton skeleton-animate'
    });
    topDiv.appendChild(h5);
    topDiv.appendChild(h2);
    borderDiv.appendChild(topDiv);
    let bottomDiv = setAttributes(document.createElement('div'), {
      'class': 'd-flex flex-column flex-md-row justify-content-between align-items-end'
    });
    let publishDateParent = setAttributes(document.createElement('div'), {
      'class': 'd-flex w-100',
    });
    let publishDate = setAttributes(document.createElement('div'), {
      'class': 'release-date-skeleton skeleton-animate',
    });
    publishDateParent.appendChild(publishDate);
    bottomDiv.appendChild(publishDateParent);
    let readMore = setAttributes(document.createElement('div'), {
      'class': 'read-more-skeleton skeleton-animate',
    });
    bottomDiv.appendChild(readMore);
    borderDiv.appendChild(bottomDiv);
    megaDiv.appendChild(borderDiv);
    return megaDiv
  }
  function getArticlesSkeleton() {
    let row = setAttributes(document.createElement('div'), {
      'class': 'row pt-4',
    });
    for (let i = 0; i < 12; i++){
      row.appendChild(getArticleSkeleton());
    }
    return row;
  }
  function changePage(page) {
    let currentUrl = window.location.href.split('&page=')[0].split('page=')[0].split('?');
    let newHrefContent = '{% url "blog:articles_content" %}';
    let newHref = '{{ listing_url }}';
    let pageString = '';
    if(currentUrl.length != 1){
      var i = currentUrl.indexOf('?');
      newHrefContent = newHrefContent + '?' + currentUrl.slice(i) + '&page=' + String(page);
      newHref = newHref + '?' + currentUrl.slice(i) + '&page=' + String(page);
    }else{
      newHrefContent = newHrefContent + '?&page=' + String(page);
      newHref = newHref + '?page=' + String(page);
    }
    loadContentSkeleton('articles-content', newHrefContent, getArticlesSkeleton());
    history.pushState('I have no idea', '{{ page.title }}', newHref);
    window.scrollTo(0, 0);
  }
	graphqlUrl = window.location.protocol + "//" + window.location.href.split('/')[2] + '/graphql';
	fetch(graphqlUrl, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({ query: '{authors, tags, categories, articles}' }),
	})
		.then(res => res.json())
		.then((res) => {
			const tagifytags = [];
			res.data.authors.forEach((name) => {
					tagifytags.push('author: ' + name);
			})
			res.data.categories.forEach((name) => {
					tagifytags.push('category: ' + name);
			})
			res.data.tags.forEach((name) => {
					tagifytags.push('tag: ' + name);
			})
			res.data.articles.forEach((name) => {
					tagifytags.push('article: ' + name);
			})
			tagify = new Tagify(
				document.getElementById('articles-filter-search'),
				{
					whitelist: tagifytags
				}
			);
			{% for search in searches %}
				tagify.addTags(['{{ search }}'])
			{% endfor %}
			if (window.location.href.indexOf("?search")) {
				setTimeout(() => {
					submitArticlesFilterForm();
				}, 5);
				var uri_dec = decodeURIComponent(window.location.href);
			}
		});
</script>
{% endblock %}

blog/templates/blog/listing_content.html
{% load i18n %}
{% load static %}
{% load wagtailcore_tags wagtailroutablepage_tags cache %}
{% block content %}
<div>
  {% if searches %}
    <div class="d-flex flex-column flex-md-row align-items-start align-items-md-center jusitfy-content-center jusitfy-content-md-start">
      <div>
        {% trans 'Articles containing: ' %} 
			</div>
			<div class="d-flex flex-row ml-md-1">
				{% for search in searches %}
					<div class="p-1 bg-white color-black rounded font-smaller mr-1">
						{{ search }}
					</div>
				{% endfor %}
				<div class="cursor-pointer d-flex align-items-center" onClick="tagify.removeAllTags(); loadArticles('{% url "blog:articles_content" %}', true);">
					<i class="icon-cancel color-white"></i>
				</div>
			</div>
    </div>
  {% endif %}
  <div class="row pt-4">
		{% for article in articles %}
			{% cache 604800 article article.id %}
				<div class="col-12 col-sm-6 col-xl-4 mb-5 article" style="min-height: 320px;">
					<div class="w-100 h-100 position-relative">
						{% if article.preview_image or article.preview_text %}
							<div class="w-100 h-100 p-3 position-absolute article-hidden-overlay"
								style="background-color: rgba(0, 0, 0, 0.8)">
								<div class="position-relative w-100 h-100 ">
									{% if article.preview_image %}
										<div class="position-relative background-image-center-cover article-preview-image w-100 h-100" 
											style="background-image: url('{% static "img/blog/food3.webp" %}');" 
											data-background-image='url("{{ article.preview_image.file.url }}")'>
											<div class="position-absolute w-100 article-preview-overlay" 
												style="bottom: 0; background-color: rgba(0, 0, 0, 0.6);">
											</div>
										</div>
									{% else %}
										<div class="position-relative background-image-center-cover article-preview-image w-100 h-100">
											{{ article.preview_text|linebreaks }}
											<div class="position-absolute w-100 article-preview-overlay" 
												style="bottom:0; background-color: rgba(0, 0, 0, 0.8);">
											</div>
										</div>
									{% endif %}
								</div>
							</div>
						{% endif %}
						<div class="border border-thick p-4 d-flex flex-column justify-content-between h-100">
							<div>
								<div class="d-flex justify-content-between mb-1 align-items-start 
								{% if aritcle.tags.all %}flex-row-reverse{% endif %}">
									<div>
										{% if article.subtitle %}
											<h5 class="mb-0">
												{{ article.subtitle }}
											</h2>
										{% else %}
											<h5 style="visibility: hidden;">
												.
											</h2>
										{% endif %}
									</div>
									<div class="d-flex flex-wrap flex-row-reverse">
										{% for tag in article.tags.all %}
											<div class="mb-1 cursor-pointer" href="{{ listing_url }}?search=tag: {{tag}}%3B%3B%3B" 
												onClick="loadArticles('{% url "blog:articles_content" %}?search=tag: {{tag}}%3B%3B%3B', true);"
												style="text-decoration: none !important;">
												<div class="d-inline article-content-tag font-smallest ml-1 border border-white p-1">
													{{ tag }}
												</div>
											</div>
										{% endfor %}
									</div>
							</div>
								<h2>
									{{ article.title }}
								</h2>
							</div>
							<a style="z-index: 1;" href="{{ article.url }}" onClick="return goToArticle('{{ article.url }}');">
								<div class="d-flex flex-column flex-md-row justify-content-between align-items-end">
									<div class="w-100">
										{{ article.get_date }}
									</div>
									<div class="pt-md-5 pl-md-2 w-100">
										<div class="d-flex justify-content-end align-items-center">
											<div class="d-flex flex-wrap align-items-center">
												<div class="font-small">
													{% trans 'read more' %}
												</div>
												<div class="long-arrow-icon ml-2">
													<div class="d-inline long-right-arrow bg-white">
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</a>
						</div>
					</div>
				</div>
			{% endcache %}
		{% endfor %}
  </div>
	{% if not articles and searches %}
		<div class="mt-4 d-flex flex-column align-items-center">
			<h3>
				{% trans 'We could not find any articles' %}
			</h3>
			{% trans 'Remove a few tags and try again.' %}
		</div>
	{% elif not articles %}
	<div class="mt-4 d-flex flex-column align-items-center">
		<h3>
			{% trans 'No articles yet' %}
		</h3>
		{% trans 'It seems like there has not been any articles written yet. Check again tomorrow!' %}
	</div>
	{% endif %}
  {% url 'blog:articles_content' as pagination_url %}
  {% trans 'Blog' as pagination_title %}
  {% include "blog/pagination.html" with page=articles %}
</div>
{% endblock %}

blog/templates/blog/pagination.html
{% load i18n blog_tags %}
<div id="pagination" class="d-flex justify-content-center align-items-center pt-4 w-100">
  <div class="d-flex justify-content-center align-items-center ">
    {% page_min page.number as page_min %}
    {% page_max page.number as page_max %}
    {% if page.paginator.num_pages != 1 %}
      {% if page.has_previous %}
        <div class="d-block mr-2 cursor-pointer" onclick="changePage({{ page.previous_page_number }})">
          <div class=" p-2 border border-white text-center d-inline-block w-h-40 pagination-page">
            <i class="icon-left"></i>
          </div>
        </div>
      {% endif %}
      {% for num in page.paginator.page_range %}
        {% if num == page.number %}
          <div class="p-2 mr-2 border border-white text-center d-inline-block pagination-page active">
            {{ page.number }}
          </div>
        {% elif num >= page_min and page_max >= num %}
          <div class="d-block mr-2 cursor-pointer" onclick="changePage({{ num }})">
            <div class="p-2 border border-white text-center d-inline-block pagination-page">
              {{ num }}
            </div>
          </div>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <div class="d-block cursor-pointer" onclick="changePage({{ page.next_page_number }})">
          <div class="p-2 border border-white text-center d-inline-blocl pagination-page">
            <i class="icon-right"></i>
          </div>
        </div>
      {% endif %}
    {% endif %}
  </div>
</div>

blog/templates/blog/pagination_unused.html
<script>
	function changePage(page){
		let currentUrl = window.location.href.split('&page=')[0].split('page=')[0].split('?');
		let newHrefContent = '{{ pagination_url }}';
		let newHref = '{{ new_url }}';
		let pageString = '';
		if(currentUrl.length != 1){
			var i = currentUrl.indexOf('?');
			newHrefContent = newHrefContent + '?' + currentUrl.slice(i) + '&page=' + String(page);
			newHref = newHref + '?' + currentUrl.slice(i) + '&page=' + String(page);
		}else{
			newHref = newHref + '?page=' + String(page);
		}
		loadContent('{{ element_replace }}', newHrefContent, 'primary');
		history.pushState('I have no idea', '{{ title }}', newHref);
		window.scrollTo(0, 0);
	}
</script>